### PR TITLE
chore(build): add support for es6 module syntax

### PR DESCRIPTION
**Pull request by icfantv**
* add new index.js file for supporting es6 module import format.

### CODE REVIEW

**Comment by icfantv** [comment]
i freely admit that i don't know if this will be sufficient.  the main code may need to be tweaked to be an IIFE as well.

**Comment by icfantv** [comment]
This should be sufficient and the main code should not need to be tweaked.

**Comment by icfantv** [comment]
Cheers, mate!

**Comment by Urigo** [comment]
sorry it took a while

**Comment by icfantv** [comment]
Hey, can you please push to node.  Thanks.

**Comment by Urigo** [comment]
@icfantv published.
Sorry it took a while, if you want, I can make you a maintainer of the repo

**Comment by icfantv** [comment]
Awesome, thanks!  As far as becoming a maintainer.  I'm already on the angular UI bootstrap team and worry that I would be spread too thin given the popularity of that project and my role within.  I'm on my mobile at the moment, so I can't check what type of work is required on spin kit.  Is development complete now and is it more just support at this phase?  If so, that could work.

Probably the first thing to do is to get your project documentation and support files up to date and we can use UIBS as a starting point for them (CHANGELOG, CONTRIBUTING, etc...)

Let me take a look when I get into work and I'll let you know.  Thanks again.

**Comment by icfantv** [comment]
@Urigo, if you want, i'm happy to help you out.  it doesn't look like there's ton of support requests so there shouldn't be a huge time commitment (certainly not like UIBS).  Thanks.

**Comment by Urigo** [comment]
@icfantv done!

**Pull request merged**
